from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

# se importa la clase(s) del 
# archivo genera_tablas
from modelo import Pais, Plataforma, Serie, Actor, Premio

# se importa información del archivo configuracion
from config import cadena_base_datos
# se genera enlace al gestor de base de
# datos
# para el ejemplo se usa la base de datos
# sqlite
engine = create_engine(cadena_base_datos)

Session = sessionmaker(bind=engine)
session = Session()

# se crea un objetos de tipo Actor
actor1 = Actor(nombre='Thomas Miller', edad=52, pais_id=5, serie_id=66)
actor2 = Actor(nombre='Valentina Müller', edad=52, pais_id=10, serie_id=13)
actor3 = Actor(nombre='Noah Botha', edad=56, pais_id=1, serie_id=107)
actor4 = Actor(nombre='Aarav Saleh', edad=48, pais_id=1, serie_id=111)
actor5 = Actor(nombre='Camila Fernández', edad=49, pais_id=1, serie_id=9)
actor6 = Actor(nombre='James Kim', edad=36, pais_id=12, serie_id=92)
actor7 = Actor(nombre='Layla Silva', edad=29, pais_id=14, serie_id=36)
actor8 = Actor(nombre='Aisha Saleh', edad=69, pais_id=9, serie_id=63)
actor9 = Actor(nombre='Hans Pereira', edad=68, pais_id=2, serie_id=65)
actor10 = Actor(nombre='Thabo Herrera', edad=37, pais_id=15, serie_id=105)
actor11 = Actor(nombre='Haruto Kim', edad=27, pais_id=14, serie_id=31)
actor12 = Actor(nombre='Olivia Rojas', edad=72, pais_id=12, serie_id=87)
actor13 = Actor(nombre='Lucía Hassan', edad=25, pais_id=8, serie_id=47)
actor14 = Actor(nombre='Andrés Morales', edad=21, pais_id=8, serie_id=26)
actor15 = Actor(nombre='Lukas Pereira', edad=31, pais_id=7, serie_id=96)
actor16 = Actor(nombre='Aarav Herrera', edad=55, pais_id=15, serie_id=4)
actor17 = Actor(nombre='Lucía Smith', edad=42, pais_id=15, serie_id=114)
actor18 = Actor(nombre='Ethan Kim', edad=27, pais_id=13, serie_id=118)
actor19 = Actor(nombre='Lucas Tanaka', edad=54, pais_id=1, serie_id=95)
actor20 = Actor(nombre='Jack Taylor', edad=50, pais_id=7, serie_id=59)
actor21 = Actor(nombre='Pierre Morales', edad=33, pais_id=11, serie_id=101)
actor22 = Actor(nombre='Arthur Saleh', edad=69, pais_id=12, serie_id=37)
actor23 = Actor(nombre='Isabella Pereira', edad=70, pais_id=8, serie_id=116)
actor24 = Actor(nombre='Lucas Mokoena', edad=67, pais_id=2, serie_id=54)
actor25 = Actor(nombre='Mina Hassan', edad=37, pais_id=13, serie_id=29)
actor26 = Actor(nombre='Miguel Dubois', edad=23, pais_id=4, serie_id=55)
actor27 = Actor(nombre='Lukas Johnson', edad=69, pais_id=13, serie_id=96)
actor28 = Actor(nombre='James Müller', edad=42, pais_id=8, serie_id=110)
actor29 = Actor(nombre='Louis Sharma', edad=34, pais_id=6, serie_id=111)
actor30 = Actor(nombre='James Okafor', edad=34, pais_id=5, serie_id=91)
actor31 = Actor(nombre='Mia Mokoena', edad=18, pais_id=6, serie_id=32)
actor32 = Actor(nombre='Valentina Sharma', edad=49, pais_id=14, serie_id=45)
actor33 = Actor(nombre='Hugo Fernández', edad=63, pais_id=12, serie_id=100)
actor34 = Actor(nombre='Valentina Méndez', edad=47, pais_id=6, serie_id=19)
actor35 = Actor(nombre='Diego Sharma', edad=59, pais_id=8, serie_id=22)
actor36 = Actor(nombre='Hans Mokoena', edad=65, pais_id=10, serie_id=75)
actor37 = Actor(nombre='Andrés Johnson', edad=49, pais_id=2, serie_id=23)
actor38 = Actor(nombre='Thabo Mokoena', edad=24, pais_id=4, serie_id=77)
actor39 = Actor(nombre='Lukas Johnson 39', edad=36, pais_id=1, serie_id=117)
actor40 = Actor(nombre='Thomas Adeyemi', edad=53, pais_id=6, serie_id=6)
actor41 = Actor(nombre='Aisha Patel', edad=41, pais_id=1, serie_id=6)
actor42 = Actor(nombre='Mina Nguyen', edad=43, pais_id=9, serie_id=116)
actor43 = Actor(nombre='Camila Silva', edad=48, pais_id=5, serie_id=100)
actor44 = Actor(nombre='Thabo Méndez', edad=25, pais_id=13, serie_id=84)
actor45 = Actor(nombre='Ethan Morales', edad=20, pais_id=13, serie_id=11)
actor46 = Actor(nombre='Miguel Okafor', edad=70, pais_id=9, serie_id=55)
actor47 = Actor(nombre='Mateo Tanaka', edad=69, pais_id=3, serie_id=116)
actor48 = Actor(nombre='Jiho Sato', edad=48, pais_id=14, serie_id=22)
actor49 = Actor(nombre='Carlos Taylor', edad=72, pais_id=1, serie_id=114)
actor50 = Actor(nombre='Lucas Walker', edad=40, pais_id=10, serie_id=117)
actor51 = Actor(nombre='Chidi Richardson', edad=55, pais_id=11, serie_id=35)
actor52 = Actor(nombre='Andrés Dubois', edad=23, pais_id=13, serie_id=103)
actor53 = Actor(nombre='Isabella Patel', edad=72, pais_id=8, serie_id=90)
actor54 = Actor(nombre='Oliver Johnson', edad=27, pais_id=6, serie_id=108)
actor55 = Actor(nombre='Camila Morales', edad=51, pais_id=1, serie_id=104)
actor56 = Actor(nombre='James Sato', edad=31, pais_id=9, serie_id=63)
actor57 = Actor(nombre='Mina Moreau', edad=52, pais_id=9, serie_id=67)
actor58 = Actor(nombre='Olivia Nguyen', edad=40, pais_id=11, serie_id=9)
actor59 = Actor(nombre='Arthur Adeyemi', edad=71, pais_id=8, serie_id=81)
actor60 = Actor(nombre='Aarav García', edad=44, pais_id=4, serie_id=54)
actor61 = Actor(nombre='Layla Costa', edad=18, pais_id=12, serie_id=12)
actor62 = Actor(nombre='Liam Fernández', edad=57, pais_id=12, serie_id=25)
actor63 = Actor(nombre='Lucas Brown', edad=67, pais_id=12, serie_id=24)
actor64 = Actor(nombre='Emma Wilson', edad=57, pais_id=13, serie_id=104)
actor65 = Actor(nombre='Mia Costa', edad=72, pais_id=14, serie_id=65)
actor66 = Actor(nombre='Camila Wilson', edad=51, pais_id=13, serie_id=81)
actor67 = Actor(nombre='Diego Park', edad=46, pais_id=14, serie_id=37)
actor68 = Actor(nombre='Mia Costa 68', edad=57, pais_id=12, serie_id=118)
actor69 = Actor(nombre='William Smith', edad=33, pais_id=4, serie_id=100)
actor70 = Actor(nombre='Rohan Nguyen', edad=39, pais_id=14, serie_id=59)
actor71 = Actor(nombre='Lucía Sharma', edad=56, pais_id=7, serie_id=3)
actor72 = Actor(nombre='Layla Pereira', edad=49, pais_id=2, serie_id=115)
actor73 = Actor(nombre='Emma Smith', edad=61, pais_id=6, serie_id=12)
actor74 = Actor(nombre='Amara Tanaka', edad=68, pais_id=14, serie_id=90)
actor75 = Actor(nombre='Lucía Dubois', edad=24, pais_id=7, serie_id=44)
actor76 = Actor(nombre='Thabo Nguyen', edad=61, pais_id=5, serie_id=67)
actor77 = Actor(nombre='Jiho Dubois', edad=45, pais_id=12, serie_id=68)
actor78 = Actor(nombre='Haruto Johnson', edad=45, pais_id=15, serie_id=118)
actor79 = Actor(nombre='Carlos Taylor 79', edad=57, pais_id=1, serie_id=57)
actor80 = Actor(nombre='Ethan Schneider', edad=31, pais_id=12, serie_id=61)
actor81 = Actor(nombre='Lukas Fernández', edad=27, pais_id=4, serie_id=97)
actor82 = Actor(nombre='Amara Martin', edad=48, pais_id=5, serie_id=36)
actor83 = Actor(nombre='Andrés Nguyen', edad=58, pais_id=3, serie_id=7)
actor84 = Actor(nombre='Hans Dubois', edad=47, pais_id=12, serie_id=106)
actor85 = Actor(nombre='Jiho Herrera', edad=61, pais_id=11, serie_id=82)
actor86 = Actor(nombre='Louis Moreau', edad=27, pais_id=3, serie_id=65)
actor87 = Actor(nombre='Pierre Patel', edad=52, pais_id=15, serie_id=72)
actor88 = Actor(nombre='Rohan Richardson', edad=26, pais_id=8, serie_id=4)
actor89 = Actor(nombre='Thomas Adeyemi Jr.', edad=39, pais_id=3, serie_id=59)
actor90 = Actor(nombre='Noah Walker', edad=31, pais_id=3, serie_id=93)
actor91 = Actor(nombre='Layla Kim', edad=23, pais_id=15, serie_id=90)
actor92 = Actor(nombre='Aarav Brown', edad=59, pais_id=10, serie_id=81)
actor93 = Actor(nombre='Sofia Williams', edad=54, pais_id=6, serie_id=118)
actor94 = Actor(nombre='Aisha Park', edad=71, pais_id=11, serie_id=16)
actor95 = Actor(nombre='Louis Martin', edad=39, pais_id=13, serie_id=36)
actor96 = Actor(nombre='Miguel Adeyemi', edad=22, pais_id=15, serie_id=27)
actor97 = Actor(nombre='Mateo Smith', edad=22, pais_id=12, serie_id=13)
actor98 = Actor(nombre='William Smith 98', edad=25, pais_id=6, serie_id=12)
actor99 = Actor(nombre='Lukas Fernández 99', edad=65, pais_id=13, serie_id=108)
actor100 = Actor(nombre='Aisha Miller', edad=53, pais_id=7, serie_id=62)



session.add(actor1)
session.add(actor2)
session.add(actor3)
session.add(actor4)
session.add(actor5)
session.add(actor6)
session.add(actor7)
session.add(actor8)
session.add(actor9)
session.add(actor10)
session.add(actor11)
session.add(actor12)
session.add(actor13)
session.add(actor14)
session.add(actor15)
session.add(actor16)
session.add(actor17)
session.add(actor18)
session.add(actor19)
session.add(actor20)
session.add(actor21)
session.add(actor22)
session.add(actor23)
session.add(actor24)
session.add(actor25)
session.add(actor26)
session.add(actor27)
session.add(actor28)
session.add(actor29)
session.add(actor30)
session.add(actor31)
session.add(actor32)
session.add(actor33)
session.add(actor34)
session.add(actor35)
session.add(actor36)
session.add(actor37)
session.add(actor38)
session.add(actor39)
session.add(actor40)
session.add(actor41)
session.add(actor42)
session.add(actor43)
session.add(actor44)
session.add(actor45)
session.add(actor46)
session.add(actor47)
session.add(actor48)
session.add(actor49)
session.add(actor50)
session.add(actor51)
session.add(actor52)
session.add(actor53)
session.add(actor54)
session.add(actor55)
session.add(actor56)
session.add(actor57)
session.add(actor58)
session.add(actor59)
session.add(actor60)
session.add(actor61)
session.add(actor62)
session.add(actor63)
session.add(actor64)
session.add(actor65)
session.add(actor66)
session.add(actor67)
session.add(actor68)    
session.add(actor69)
session.add(actor70)
session.add(actor71)
session.add(actor72)    
session.add(actor73)
session.add(actor74)
session.add(actor75)
session.add(actor76)
session.add(actor77)
session.add(actor78)
session.add(actor79)
session.add(actor80)
session.add(actor81)
session.add(actor82)
session.add(actor83)
session.add(actor84)
session.add(actor85)
session.add(actor86)
session.add(actor87)
session.add(actor88)
session.add(actor89)
session.add(actor90)
session.add(actor91)
session.add(actor92)
session.add(actor93)
session.add(actor94)
session.add(actor95)
session.add(actor96)
session.add(actor97)
session.add(actor98)
session.add(actor99)
session.add(actor100)

# se confirma las transacciones
session.commit()
