from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

# se importa la clase(s) del 
# archivo modelo
from modelo import  Serie, Plataforma, Pais
# se importa información del archivo configuracion
from config import cadena_base_datos

# se genera enlace al gestor de base de
# datos
# para el ejemplo se usa la base de datos
# sqlite
engine = create_engine(cadena_base_datos)

Session = sessionmaker(bind=engine)
session = Session()

# Se crean objetos de tipo Serie
serie1 = Serie(titulo='Ruta Antigua', genero='Documental', anio_estreno=2016, temporadas=6, plataforma_id=2, pais_id=3)
serie2 = Serie(titulo='Niebla Rota', genero='Documental', anio_estreno=2021, temporadas=2, plataforma_id=19, pais_id=13)
serie3 = Serie(titulo='Código Salvaje', genero='Histórica', anio_estreno=2025, temporadas=7, plataforma_id=1, pais_id=11)
serie4 = Serie(titulo='Frontera Perdida', genero='Romance', anio_estreno=2011, temporadas=8, plataforma_id=20, pais_id=5)
serie5 = Serie(titulo='Secreto Azul', genero='Crimen', anio_estreno=2022, temporadas=4, plataforma_id=20, pais_id=3)
serie6 = Serie(titulo='Amanecer Circular', genero='Suspenso', anio_estreno=2023, temporadas=1, plataforma_id=18, pais_id=4)
serie7 = Serie(titulo='Herencia Circular', genero='Suspenso', anio_estreno=2015, temporadas=3, plataforma_id=3, pais_id=7)
serie8 = Serie(titulo='Ciudad Antigua', genero='Fantasía', anio_estreno=2012, temporadas=4, plataforma_id=7, pais_id=14)
serie9 = Serie(titulo='Amanecer Oscura', genero='Histórica', anio_estreno=2012, temporadas=6, plataforma_id=5, pais_id=3)
serie10 = Serie(titulo='Niebla Antigua', genero='Acción', anio_estreno=2018, temporadas=7, plataforma_id=7, pais_id=12)
serie11 = Serie(titulo='Frontera Del Norte', genero='Drama', anio_estreno=2016, temporadas=6, plataforma_id=5, pais_id=5)
serie12 = Serie(titulo='Herencia Lejana', genero='Histórica', anio_estreno=2010, temporadas=4, plataforma_id=1, pais_id=14)
serie13 = Serie(titulo='Memoria Azul', genero='Comedia', anio_estreno=2018, temporadas=4, plataforma_id=12, pais_id=3)
serie14 = Serie(titulo='Memoria Salvaje', genero='Fantasía', anio_estreno=2014, temporadas=4, plataforma_id=18, pais_id=9)
serie15 = Serie(titulo='Destino Infinita', genero='Drama', anio_estreno=2018, temporadas=2, plataforma_id=16, pais_id=13)
serie16 = Serie(titulo='Niebla Oscura', genero='Crimen', anio_estreno=2009, temporadas=1, plataforma_id=17, pais_id=9)
serie17 = Serie(titulo='Destino Dorada', genero='Suspenso', anio_estreno=2024, temporadas=2, plataforma_id=3, pais_id=6)
serie18 = Serie(titulo='Camino Antigua', genero='Crimen', anio_estreno=2025, temporadas=7, plataforma_id=12, pais_id=12)
serie19 = Serie(titulo='Imperio Profunda', genero='Fantasía', anio_estreno=2023, temporadas=6, plataforma_id=4, pais_id=11)
serie20 = Serie(titulo='Camino Del Norte', genero='Ciencia ficción', anio_estreno=2007, temporadas=4, plataforma_id=2, pais_id=11)
serie21 = Serie(titulo='Código Eterna', genero='Crimen', anio_estreno=2024, temporadas=2, plataforma_id=8, pais_id=12)
serie22 = Serie(titulo='Luz Profunda', genero='Documental', anio_estreno=2005, temporadas=3, plataforma_id=6, pais_id=13)
serie23 = Serie(titulo='Puerto Central', genero='Drama', anio_estreno=2016, temporadas=5, plataforma_id=6, pais_id=7)
serie24 = Serie(titulo='Ciudad Nueva', genero='Documental', anio_estreno=2019, temporadas=4, plataforma_id=17, pais_id=4)
serie25 = Serie(titulo='Código Rota', genero='Fantasía', anio_estreno=2007, temporadas=5, plataforma_id=15, pais_id=4)
serie26 = Serie(titulo='Mirada Perdida', genero='Drama', anio_estreno=2005, temporadas=2, plataforma_id=20, pais_id=9)
serie27 = Serie(titulo='Reino Salvaje', genero='Crimen', anio_estreno=2011, temporadas=3, plataforma_id=13, pais_id=1)
serie28 = Serie(titulo='Camino Del Sur', genero='Suspenso', anio_estreno=2018, temporadas=7, plataforma_id=3, pais_id=3)
serie29 = Serie(titulo='Camino Brillante', genero='Acción', anio_estreno=2006, temporadas=2, plataforma_id=3, pais_id=11)
serie30 = Serie(titulo='Herencia Final', genero='Romance', anio_estreno=2010, temporadas=5, plataforma_id=5, pais_id=7)
serie31 = Serie(titulo='Memoria Brillante', genero='Comedia', anio_estreno=2015, temporadas=5, plataforma_id=15, pais_id=13)
serie32 = Serie(titulo='Marea Salvaje', genero='Acción', anio_estreno=2009, temporadas=1, plataforma_id=19, pais_id=6)
serie33 = Serie(titulo='Marea Azul', genero='Fantasía', anio_estreno=2013, temporadas=8, plataforma_id=19, pais_id=4)
serie34 = Serie(titulo='Ruta Oscura', genero='Drama', anio_estreno=2015, temporadas=6, plataforma_id=9, pais_id=9)
serie35 = Serie(titulo='Medianoche Del Sur', genero='Crimen', anio_estreno=2014, temporadas=6, plataforma_id=18, pais_id=7)
serie36 = Serie(titulo='Archivo Central', genero='Documental', anio_estreno=2018, temporadas=4, plataforma_id=1, pais_id=12)
serie37 = Serie(titulo='Casa Circular', genero='Histórica', anio_estreno=2007, temporadas=4, plataforma_id=1, pais_id=9)
serie38 = Serie(titulo='Mirada Secreta', genero='Fantasía', anio_estreno=2019, temporadas=8, plataforma_id=15, pais_id=5)
serie39 = Serie(titulo='Sombras Central', genero='Crimen', anio_estreno=2006, temporadas=4, plataforma_id=15, pais_id=10)
serie40 = Serie(titulo='Silencio Rota', genero='Romance', anio_estreno=2014, temporadas=3, plataforma_id=6, pais_id=15)
serie41 = Serie(titulo='Estación Circular', genero='Drama', anio_estreno=2022, temporadas=1, plataforma_id=12, pais_id=2)
serie42 = Serie(titulo='Luz Profunda 77', genero='Acción', anio_estreno=2012, temporadas=3, plataforma_id=2, pais_id=14)
serie43 = Serie(titulo='Medianoche Eterna', genero='Acción', anio_estreno=2009, temporadas=8, plataforma_id=11, pais_id=9)
serie44 = Serie(titulo='Casa Azul', genero='Comedia', anio_estreno=2011, temporadas=8, plataforma_id=17, pais_id=15)
serie45 = Serie(titulo='Marea Perdida', genero='Crimen', anio_estreno=2019, temporadas=8, plataforma_id=12, pais_id=13)
serie46 = Serie(titulo='Reino Central', genero='Documental', anio_estreno=2019, temporadas=3, plataforma_id=13, pais_id=5)
serie47 = Serie(titulo='Medianoche Dorada', genero='Ciencia ficción', anio_estreno=2007, temporadas=5, plataforma_id=6, pais_id=14)
serie48 = Serie(titulo='Primera Oscura', genero='Crimen', anio_estreno=2007, temporadas=3, plataforma_id=4, pais_id=13)
serie49 = Serie(titulo='Memoria Rota', genero='Suspenso', anio_estreno=2010, temporadas=5, plataforma_id=12, pais_id=12)
serie50 = Serie(titulo='Pacto Azul', genero='Fantasía', anio_estreno=2019, temporadas=7, plataforma_id=8, pais_id=9)
serie51 = Serie(titulo='Estación Central', genero='Romance', anio_estreno=2013, temporadas=6, plataforma_id=17, pais_id=9)
serie52 = Serie(titulo='Puerto Brillante', genero='Acción', anio_estreno=2014, temporadas=8, plataforma_id=20, pais_id=3)
serie53 = Serie(titulo='Camino Central', genero='Documental', anio_estreno=2024, temporadas=5, plataforma_id=15, pais_id=9)
serie54 = Serie(titulo='Último Brillante', genero='Acción', anio_estreno=2023, temporadas=5, plataforma_id=20, pais_id=3)
serie55 = Serie(titulo='Mirada Profunda', genero='Crimen', anio_estreno=2014, temporadas=7, plataforma_id=7, pais_id=5)
serie56 = Serie(titulo='Secreto Oscura', genero='Drama', anio_estreno=2013, temporadas=3, plataforma_id=12, pais_id=4)
serie57 = Serie(titulo='Silencio Dorada', genero='Documental', anio_estreno=2021, temporadas=6, plataforma_id=18, pais_id=5)
serie58 = Serie(titulo='Destino Del Sur', genero='Acción', anio_estreno=2014, temporadas=1, plataforma_id=18, pais_id=5)
serie59 = Serie(titulo='Archivo Central 42', genero='Comedia', anio_estreno=2009, temporadas=1, plataforma_id=15, pais_id=2)
serie60 = Serie(titulo='Refugio Central', genero='Suspenso', anio_estreno=2007, temporadas=5, plataforma_id=9, pais_id=10)
serie61 = Serie(titulo='Pacto Nueva', genero='Acción', anio_estreno=2024, temporadas=5, plataforma_id=5, pais_id=12)
serie62 = Serie(titulo='Primera Perdida', genero='Histórica', anio_estreno=2011, temporadas=2, plataforma_id=16, pais_id=11)
serie63 = Serie(titulo='Luz Azul', genero='Ciencia ficción', anio_estreno=2006, temporadas=7, plataforma_id=20, pais_id=10)
serie64 = Serie(titulo='Último Central', genero='Romance', anio_estreno=2017, temporadas=4, plataforma_id=1, pais_id=1)
serie65 = Serie(titulo='Reino Perdida', genero='Crimen', anio_estreno=2005, temporadas=7, plataforma_id=18, pais_id=15)
serie66 = Serie(titulo='Horizonte Secreta', genero='Fantasía', anio_estreno=2024, temporadas=4, plataforma_id=3, pais_id=2)
serie67 = Serie(titulo='Refugio Salvaje', genero='Crimen', anio_estreno=2015, temporadas=7, plataforma_id=19, pais_id=3)
serie68 = Serie(titulo='Herencia Azul', genero='Crimen', anio_estreno=2018, temporadas=1, plataforma_id=11, pais_id=4)
serie69 = Serie(titulo='Horizonte Invisible', genero='Comedia', anio_estreno=2005, temporadas=2, plataforma_id=9, pais_id=10)
serie70 = Serie(titulo='Herencia Rota', genero='Comedia', anio_estreno=2017, temporadas=5, plataforma_id=2, pais_id=9)
serie71 = Serie(titulo='Ciudad Final', genero='Comedia', anio_estreno=2018, temporadas=5, plataforma_id=20, pais_id=11)
serie72 = Serie(titulo='Raíces Central', genero='Comedia', anio_estreno=2009, temporadas=2, plataforma_id=15, pais_id=13)
serie73 = Serie(titulo='Horizonte Brillante', genero='Crimen', anio_estreno=2008, temporadas=4, plataforma_id=1, pais_id=1)
serie74 = Serie(titulo='Amanecer Infinita', genero='Fantasía', anio_estreno=2006, temporadas=1, plataforma_id=6, pais_id=14)
serie75 = Serie(titulo='Código Del Sur', genero='Histórica', anio_estreno=2014, temporadas=1, plataforma_id=17, pais_id=13)
serie76 = Serie(titulo='Luz Salvaje', genero='Crimen', anio_estreno=2024, temporadas=1, plataforma_id=2, pais_id=10)
serie77 = Serie(titulo='Imperio Antigua', genero='Romance', anio_estreno=2009, temporadas=8, plataforma_id=13, pais_id=6)
serie78 = Serie(titulo='Raíces Del Sur', genero='Documental', anio_estreno=2007, temporadas=5, plataforma_id=17, pais_id=5)
serie79 = Serie(titulo='Horizonte Secreta 4', genero='Documental', anio_estreno=2006, temporadas=7, plataforma_id=4, pais_id=7)
serie80 = Serie(titulo='Amanecer Dorada', genero='Crimen', anio_estreno=2017, temporadas=4, plataforma_id=10, pais_id=6)
serie81 = Serie(titulo='Silencio Del Sur', genero='Romance', anio_estreno=2025, temporadas=4, plataforma_id=14, pais_id=8)
serie82 = Serie(titulo='Medianoche Final', genero='Crimen', anio_estreno=2011, temporadas=6, plataforma_id=20, pais_id=2)
serie83 = Serie(titulo='Archivo Final', genero='Ciencia ficción', anio_estreno=2025, temporadas=5, plataforma_id=1, pais_id=14)
serie84 = Serie(titulo='Marea Invisible', genero='Fantasía', anio_estreno=2011, temporadas=2, plataforma_id=19, pais_id=4)
serie85 = Serie(titulo='Raíces Secreta', genero='Suspenso', anio_estreno=2016, temporadas=5, plataforma_id=2, pais_id=7)
serie86 = Serie(titulo='Código Secreta', genero='Ciencia ficción', anio_estreno=2022, temporadas=5, plataforma_id=6, pais_id=6)
serie87 = Serie(titulo='Imperio Central', genero='Drama', anio_estreno=2023, temporadas=8, plataforma_id=19, pais_id=2)
serie88 = Serie(titulo='Marea Central', genero='Histórica', anio_estreno=2010, temporadas=3, plataforma_id=4, pais_id=1)
serie89 = Serie(titulo='Primera Salvaje', genero='Suspenso', anio_estreno=2017, temporadas=7, plataforma_id=11, pais_id=10)
serie90 = Serie(titulo='Voces Lejana', genero='Histórica', anio_estreno=2023, temporadas=6, plataforma_id=13, pais_id=3)
serie91 = Serie(titulo='Imperio Final', genero='Documental', anio_estreno=2019, temporadas=7, plataforma_id=19, pais_id=5)
serie92 = Serie(titulo='Imperio Antigua 12', genero='Acción', anio_estreno=2021, temporadas=7, plataforma_id=19, pais_id=11)
serie93 = Serie(titulo='Primera Circular', genero='Romance', anio_estreno=2017, temporadas=6, plataforma_id=6, pais_id=12)
serie94 = Serie(titulo='Mirada Azul', genero='Romance', anio_estreno=2016, temporadas=2, plataforma_id=20, pais_id=10)
serie95 = Serie(titulo='Sombras Del Sur', genero='Histórica', anio_estreno=2025, temporadas=5, plataforma_id=20, pais_id=14)
serie96 = Serie(titulo='Último Final', genero='Acción', anio_estreno=2014, temporadas=5, plataforma_id=1, pais_id=6)
serie97 = Serie(titulo='Sombras Antigua', genero='Comedia', anio_estreno=2015, temporadas=7, plataforma_id=18, pais_id=3)
serie98 = Serie(titulo='Voces Profunda', genero='Documental', anio_estreno=2015, temporadas=4, plataforma_id=10, pais_id=1)
serie99 = Serie(titulo='Reino Secreta', genero='Fantasía', anio_estreno=2023, temporadas=1, plataforma_id=15, pais_id=2)
serie100 = Serie(titulo='Camino Salvaje', genero='Fantasía', anio_estreno=2008, temporadas=2, plataforma_id=7, pais_id=13)
serie101 = Serie(titulo='Silencio Profunda', genero='Romance', anio_estreno=2012, temporadas=7, plataforma_id=15, pais_id=11)
serie102 = Serie(titulo='Refugio Eterna', genero='Ciencia ficción', anio_estreno=2017, temporadas=4, plataforma_id=20, pais_id=1)
serie103 = Serie(titulo='Estación Invisible', genero='Romance', anio_estreno=2007, temporadas=1, plataforma_id=2, pais_id=6)
serie104 = Serie(titulo='Amanecer Secreta', genero='Suspenso', anio_estreno=2022, temporadas=5, plataforma_id=2, pais_id=10)
serie105 = Serie(titulo='Archivo Circular', genero='Comedia', anio_estreno=2021, temporadas=3, plataforma_id=7, pais_id=13)
serie106 = Serie(titulo='Primera Antigua', genero='Romance', anio_estreno=2009, temporadas=3, plataforma_id=5, pais_id=13)
serie107 = Serie(titulo='Camino Infinita', genero='Crimen', anio_estreno=2023, temporadas=3, plataforma_id=12, pais_id=13)
serie108 = Serie(titulo='Amanecer Azul', genero='Comedia', anio_estreno=2025, temporadas=3, plataforma_id=15, pais_id=11)
serie109 = Serie(titulo='Horizonte Brillante 81', genero='Ciencia ficción', anio_estreno=2019, temporadas=6, plataforma_id=8, pais_id=8)
serie110 = Serie(titulo='Frontera Brillante', genero='Comedia', anio_estreno=2005, temporadas=1, plataforma_id=6, pais_id=12)
serie111 = Serie(titulo='Camino Infinita 18', genero='Romance', anio_estreno=2006, temporadas=1, plataforma_id=3, pais_id=5)
serie112 = Serie(titulo='Destino Profunda', genero='Fantasía', anio_estreno=2017, temporadas=8, plataforma_id=5, pais_id=6)
serie113 = Serie(titulo='Herencia Secreta', genero='Fantasía', anio_estreno=2023, temporadas=2, plataforma_id=9, pais_id=9)
serie114 = Serie(titulo='Medianoche Final 55', genero='Comedia', anio_estreno=2011, temporadas=6, plataforma_id=14, pais_id=4)
serie115 = Serie(titulo='Amanecer Central', genero='Drama', anio_estreno=2011, temporadas=1, plataforma_id=4, pais_id=5)
serie116 = Serie(titulo='Raíces Final', genero='Fantasía', anio_estreno=2005, temporadas=6, plataforma_id=8, pais_id=11)
serie117 = Serie(titulo='Voces Salvaje', genero='Crimen', anio_estreno=2007, temporadas=1, plataforma_id=3, pais_id=11)
serie118 = Serie(titulo='Marea Eterna', genero='Documental', anio_estreno=2022, temporadas=1, plataforma_id=13, pais_id=12)
serie119 = Serie(titulo='Mirada Rota', genero='Romance', anio_estreno=2007, temporadas=4, plataforma_id=11, pais_id=10)
serie120 = Serie(titulo='Destino Secreta', genero='Histórica', anio_estreno=2018, temporadas=4, plataforma_id=2, pais_id=7)

session.add(serie1)
session.add(serie2) 
session.add(serie3)
session.add(serie4)
session.add(serie5)
session.add(serie6)
session.add(serie7)
session.add(serie8)
session.add(serie9)
session.add(serie10)
session.add(serie11)
session.add(serie12)
session.add(serie13)
session.add(serie14)    
session.add(serie15)
session.add(serie16)
session.add(serie17)
session.add(serie18)
session.add(serie19)
session.add(serie20)
session.add(serie21)
session.add(serie22)
session.add(serie23)
session.add(serie24)
session.add(serie25)
session.add(serie26)
session.add(serie27)
session.add(serie28)
session.add(serie29)
session.add(serie30)
session.add(serie31)
session.add(serie32)
session.add(serie33)    
session.add(serie34)
session.add(serie35)
session.add(serie36)
session.add(serie37)
session.add(serie38)
session.add(serie39)
session.add(serie40)
session.add(serie41)
session.add(serie42)
session.add(serie43)
session.add(serie44)
session.add(serie45)
session.add(serie46)
session.add(serie47)
session.add(serie48)
session.add(serie49)
session.add(serie50)
session.add(serie51)
session.add(serie52)
session.add(serie53)
session.add(serie54)
session.add(serie55)
session.add(serie56)
session.add(serie57)
session.add(serie58)
session.add(serie59)
session.add(serie60)
session.add(serie61)
session.add(serie62)
session.add(serie63)
session.add(serie64)
session.add(serie65)
session.add(serie66)
session.add(serie67)
session.add(serie68)
session.add(serie69)
session.add(serie70)
session.add(serie71)
session.add(serie72)
session.add(serie73)
session.add(serie74)
session.add(serie75)
session.add(serie76)
session.add(serie77)
session.add(serie78)
session.add(serie79)
session.add(serie80)
session.add(serie81)
session.add(serie82)
session.add(serie83)
session.add(serie84)
session.add(serie85)
session.add(serie86)
session.add(serie87)
session.add(serie88)
session.add(serie89)
session.add(serie90)
session.add(serie91)
session.add(serie92)
session.add(serie93)
session.add(serie94)
session.add(serie95)
session.add(serie96)
session.add(serie97)
session.add(serie98)
session.add(serie99)
session.add(serie100)
session.add(serie101)
session.add(serie102)
session.add(serie103)
session.add(serie104)
session.add(serie105)
session.add(serie106)
session.add(serie107)
session.add(serie108)
session.add(serie109)
session.add(serie110)
session.add(serie111)
session.add(serie112)
session.add(serie113)
session.add(serie114)
session.add(serie115)
session.add(serie116)
session.add(serie117)
session.add(serie118)
session.add(serie119)
session.add(serie120)

session.commit()